### ISSUE TITLE
word dropout tying

### ISSUE THREAD

**Issue by helson73** [yaringal/BayesianRNN#4]
Hi, thank you for your excellent work.
I found some weird parts in source code.  
In  main_new_dropout_SOTA_v3.lua, line 216
`local x = state.data[state.pos + i - 1]`
Isn't it should be
`local x = state.data[state.pos + i - 1][b]`
??
and line 218
`        if state.data[state.pos + j - 1] == x then`
Isn't it should be
`        if state.data[state.pos + j - 1][b] == x then`
??
Other LM demos have the same problem.
If batch words are compared, there is few chance that they are completely equal, therefore word dropouts are not tied. I am wondering whether your result in your paper use the same source code?

**Comment by yaringal** [comment]
Hi @helson73, thanks for noticing that! I fixed the code and re-ran the experiments with `Variational (untied weights) large LSTM`. New results are:

- Validation set perplexity: 77.457 (down from 77.9)
- Test set perplexity: 75.112 (down from 75.2)
- Test set perplexity (MC): 73.318975131 (down from 73.4)

**Comment by helson73** [comment]
@yaringal That's right, I got similar result with yours.
